# Generated by Django 3.2.8 on 2022-06-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('price_in_dollar', models.IntegerField()),
                ('price_in_rub', models.IntegerField()),
                ('date_delivery', models.CharField(max_length=12)),
            ],
        ),
    ]
